/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Indexer */

#ifndef _Included_Indexer
#define _Included_Indexer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Indexer
 * Method:    buildIndex
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Indexer_buildIndex
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     Indexer
 * Method:    TFIDFSearch
 * Signature: ([Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_Indexer_TFIDFSearch
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
