dev:
    cd hw5 && cargo build
    mkdir -p submit
    rm -rf submit/*
    cp src/BuildIndex.java submit
    cp src/Indexer.java submit
    cp src/TFIDFSearch.java submit
    deno run --allow-read=. --allow-write=submit ./embed_dylib.js submit/Indexer.java hw5/target/debug/libhw5.so
    cd submit && javac BuildIndex.java Indexer.java TFIDFSearch.java

release:
    cd hw5 && cargo build --release
    mkdir -p submit
    rm -rf submit/*
    cp src/BuildIndex.java submit
    cp src/Indexer.java submit
    cp src/TFIDFSearch.java submit
    deno run --allow-read=. --allow-write=submit ./embed_dylib.js submit/Indexer.java hw5/target/release/libhw5.so
