dev:
    cd hw5 && cargo build
    mkdir -p submit
    rm -rf submit/*
    cp src/BuildIndex.java submit
    cp src/Indexer.java submit
    cp src/TFIDFSearch.java submit
    deno run --allow-read=. --allow-write=submit ./embed_dylib.js submit/Indexer.java hw5/target/debug/libhw5.so
    cd submit && javac BuildIndex.java Indexer.java TFIDFSearch.java

release:
    cd hw5 && RUSTFLAGS="-Ctarget-cpu=x86-64-v3" cargo build --release
    mkdir -p submit
    rm -rf submit/*
    cp src/BuildIndex.java submit
    cp src/Indexer.java submit
    cp src/TFIDFSearch.java submit
    deno run --allow-read=. --allow-write=submit ./embed_dylib.js submit/Indexer.java hw5/target/release/libhw5.so

optimize:
    # cd hw5 && RUSTFLAGS="-Ctarget-cpu=x86-64-v4 -Ctarget-feature=+avx2" cargo pgo build
    cd hw5 && RUSTFLAGS="-Ctarget-cpu=x86-64-v3" cargo pgo build
    mkdir -p submit
    rm -rf submit/*
    cp src/BuildIndex.java submit
    cp src/Indexer.java submit
    cp src/TFIDFSearch.java submit
    deno run --allow-read=. --allow-write=submit ./embed_dylib.js submit/Indexer.java hw5/target/x86_64-unknown-linux-gnu/release/libhw5.so
    cd submit && javac BuildIndex.java Indexer.java TFIDFSearch.java
    cd submit && java BuildIndex ../testcase/corpus0.txt
    cd submit && java TFIDFSearch corpus0 ../testcase/tc3.txt
    cd submit && java TFIDFSearch corpus0 ../testcase/tc4.txt
    cd hw5 && RUSTFLAGS="-Ctarget-cpu=x86-64-v4" cargo pgo optimize
    rm submit/Indexer.java
    cp src/Indexer.java submit
    deno run --allow-read=. --allow-write=submit ./embed_dylib.js submit/Indexer.java hw5/target/x86_64-unknown-linux-gnu/release/libhw5.so


